### ISSUE TITLE
Applying Styles Programmatically

### ISSUE THREAD

**Issue by MatthewPatience** [daniel-hall/Stylish#26]
What would be the best way to apply styles from a stylesheet programmatically, for views that need to be generated at runtime?

**Comment by daniel-hall** [comment]
As long as the views conform to the `Styleable` protocol (see the built-in Styleable components for reference), then you can simply set the `styles` property after generating the views.

For example:

```
let generatedView = MyStyleableView()
addSubview(generatedView)
generatedView.styles = "basic, active"
```

or:

```
let generatedView = isError ? MyStyleableErrorView() : MyStyleableInformationView()
addSubview(generatedView)
(generatedView as? Styleable)?.styles = "basic, active"
```

**Comment by MatthewPatience** [comment]
Perfect! Thank you!
