### ISSUE TITLE
Setting UIButton.title font

### ISSUE THREAD

**Issue by adamn** [daniel-hall/Stylish#4]
I have a style for UIButtons that requires the use of a custom font.  I was thinking I would set UIButton.title to a certain font ... but that doesn't seem to be possible.  Do you have an example of how to set the font of a UIButton title?

**Comment by daniel-hall** [comment]
Hi @adamn ,

Thanks for opening an issue for this and my apologies for not seeing it until today.  I added "titleFont" as styleable UIButton property in pull request https://github.com/daniel-hall/Stylish/pull/6 and it's now in the master branch.

To use it, just reference it inside a button style class, something like this:

``` swift
struct MyButtonStyle : StyleClass {
    var stylePropertySets = StylePropertySetCollection()
    init() {
        UIButton.titleColorForNormalState = UIColor(red:0.21, green:0.29, blue:0.36, alpha:1.0)
        UIButton.titleColorForHighlightedState = UIColor(red:0.18, green:0.24, blue:0.31, alpha:1.0)
        UIButton.titleColorForDisabledState = UIColor(red:0.18, green:0.24, blue:0.31, alpha:1.0)
        UIButton.titleFont = UIFont(name: "Papyrus", size: 14.0) // <--- Here is where it's used
        UIView.backgroundColor = UIColor(white: 0.82, alpha: 1.0)
        }
    }
```

Now, when you assign the style "MyButtonStyle" to a button in a storyboard it will use the font you specified above.
