### ISSUE TITLE
Runtime JSON style

### ISSUE THREAD

**Issue by ypawar82** [daniel-hall/Stylish#8]
2 scenarios

1. In myapp settings screen, I have a table view which lists 3 different theme names. If I select one theme, tableview dismisses and I would like to see the new theme applied (I have JSON stylesheet), is this possible using stylish ? and howto ?

2. I would like to download JSON stylesheet from server when app starts and see this new theme applied.

Please advise.

**Comment by daniel-hall** [comment]
Hi @ypawar82,

1.  The Stylish Example app has a similar functionality that allows you to dynamically switch between global stylesheets.  Take a look at the MainViewController.swift file; the single method in there switches the global stylesheet (theme).  All you need to do is set the global static var `Stylish.GlobalStylesheet`, e.g. `Stylish.GlobalStylesheet = YourStylesheetClass.self`

2. To download and use a JSON stylesheet that only styles the standard controls that Stylish has built in (StyleableUIView, StyleableUILabel, StyleableUIButton), download the file and save it with the name "stylesheet.json" to the application's cache directory.  Then set `Stylish.GlobalStylesheet = JSONStylesheet.self`.  That will apply the just-downloaded stylesheet to the whole app. 

If you are using your own custom components that you have extended to make Styleable, you need to subclass JSONStylesheet.swift as shown in the example project to register the additional style property sets you created. You would still download the JSON from the server and save it as "stylesheet.json" in the caches directory, but then you would set `Stylish.GlobalStylesheet = YourSubclassOfJSONStylesheet.self`

Hope that serves your needs.  Please let me know so I can close the issue or follow up as needed!

**Comment by ypawar82** [comment]
Cool !!
Let's close this issue.
Thank you !!

**Comment by daniel-hall** [comment]
Done!
